apiVersion: v1
kind: Pod
metadata:
  name: ...
  labels:
    app: ...
spec:
  containers:
    - name: ...
      image: ...
      command:
        - sh
        - "-c"
        - echo Hello, World! && sleep 3600